### ISSUE TITLE
Penambahan kolom pemeriksaan spt versi 0.3

### ISSUE THREAD

**Issue by dirr** [simaya/simaya#187]
agar lebih informatif agar bisa di kombinasikan antar alur pemeriksaan dengan tabel pemeriksaan
![screen shot 2014-10-21 at 7 55 43 am](https://cloud.githubusercontent.com/assets/8622097/4711695/ea262d56-58be-11e4-8c58-1fb5a8ba9617.png)
![screen shot 2014-10-21 at 8 07 45 am](https://cloud.githubusercontent.com/assets/8622097/4711697/ed03cd94-58be-11e4-8b15-e6a54e82aaec.png)
ditabel hasil pemeriksaan ada status disetujui, ditolak dll

**Comment by cho2** [comment]
Sepertinya sudah cukup terakomodir
