### ISSUE TITLE
Tidak bisa menmapilkan pratinjau surat

### ISSUE THREAD

**Issue by emhaye** [simaya/simaya#201]
![pratinjau](https://cloud.githubusercontent.com/assets/1796162/4794854/86d99074-5df7-11e4-84bd-ccfb6f31e1c1.png)

Log dari console:

``` sh
Uncaught TypeError: Cannot read property 'length' of undefined letter.js:232
```

Log dari terminal

``` sh
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

Catatan: node restart sendiri

**Comment by soulblank** [comment]
Saya menggunakan siMAYA v.4 dengan ubuntu server 16 dan 14 dan
Permasalahan yang sama tidak bisa preview file pdf
GET /letter/view-pdf-stub/57f5a046ea5555870956b0b3/57f5a08cea5555870956b0b4 304 29ms
GET /notification/list 304 8ms
GET /calendar/getAlarm 304 6ms
GET /announcement 200 12ms - 0b
{ [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
GET /letter/metadata/57f5a08cea5555870956b0b4 400 43ms - 2b

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)

**Comment by soulblank** [comment]
Saya sudah pasang  libreoffice dan graphicsmagick, tetapi masih error, mohon pencerahannya
