### ISSUE TITLE
Menu agenda surat keluar manual >> ada pilihan ambil dari pangkalan data juga. Gunanya buat brodcast surat di dalam satu kab/kota/prov

### ISSUE THREAD

**Issue by simaya** [simaya/simaya#253]
![screen shot 2014-12-16 at 8 04 00 am](https://cloud.githubusercontent.com/assets/8026127/5447021/29b67950-84fa-11e4-92fa-478d5e1d39db.png)

**Comment by emhaye** [comment]
Duplicate #237
