### ISSUE TITLE
Secara random, akun yang baru dibuat, untuk  surat masuk tiba2 isi suratnya sangat banyak dan dari instansi lain.

### ISSUE THREAD

**Issue by simaya** [simaya/simaya#254]
Kejadian dari salah satu akun TU di Kota Tegal, tapi setelah di refresh normal lagi isi surat masuk di akun tersebut
Akun : admin.surat.diskimtaru dan admin.surat.bagumum

**Comment by cho2** [comment]
![cuplikan layar dari 2015-01-28 14 39 45](https://cloud.githubusercontent.com/assets/6271071/5934015/8513bb82-a6fb-11e4-8531-c8c7bc865a4e.png)

Saya coba di layanan dengan akun, struktur dan instansi baru. Tidak ada surat masuk sama sekali.
