### ISSUE TITLE
siMAYA-L: akun pengguna yang didapat dari sinkronisasi master masih bisa login di lokal

### ISSUE THREAD

**Issue by dotovr** [simaya/simaya#272]
Semua akun hasil sinkron dari master masih bisa login di lokal

**Comment by herpiko** [comment]
Tambahan :
- akun masih login dengan uuid.username
- tidak sinkron jika nama instansi sama di master dan lokal

**Comment by dotovr** [comment]
Terima kasih pak, tiketnya saya pisahkan #293 #295

**Comment by dotovr** [comment]
Tiket ini saya buka kembali

Saat ini akun yang didapat dari master, bisa login di lokal

**Comment by dotovr** [comment]
Terima kasih pak
