### ISSUE TITLE
Filter berkas unggah

### ISSUE THREAD

**Issue by dotovr** [simaya/simaya#280]
* Linimasa
* Surat Keluar
* Agenda masuk/keluar
* Berkas

Dibuat filter hanya bisa unggah .png .jpg dan .pdf
Khusus pada webodf filter hanya bisa unggah berkas .odt

**Comment by herpiko** [comment]
Ketinggalan 
- pada Agenda keluar

**Comment by dotovr** [comment]
Terima kasih pak

**Comment by bonovasuharko** [comment]
di Profile masih dapat di unggah .html.jpg

**Comment by dotovr** [comment]
aplikasi mengecek ektensi dari berkas yang di unggah
jika yang diunggah .html.jpg ya ini .jpg, kalo yang diunggah .html ini akan ditolak saat tombol simpan ditekan

**Comment by bonovasuharko** [comment]
tetapi jadi bs tereksekusi pak .htmlnya apa tidak berbahaya,apa ga
seharusna filena di scan bin nya jd klo ektensinya double tetep ga bs..
15 Jan 2015 09:21, "Mahyuddin Idram Ahmad" <notifications@github.com>
menulis:

**Comment by dotovr** [comment]
berkas unggahan tidak tereksekusi

**Comment by dotovr** [comment]
Berkas yang diunggah itu cuma masukkan ke dalam basis data saja mentah2.
Berkas yang diunggah tidak akan diproses sama sekali
