### ISSUE TITLE
Fitur Ambil dari Pangkalan Data hilang pada saat buat surat

### ISSUE THREAD

**Issue by dirr** [simaya/simaya#285]
Ini terjadi pada saat kita pilih Surat Keluar-> Buat Surat, tampilannya langsung spt ini:

![screen shot 2015-01-05 at 6 57 47 pm](https://cloud.githubusercontent.com/assets/8622097/5612775/cb160a8c-950c-11e4-9aae-54fcb0be9257.png)
menu dari pangkalan data tidak mncul sehingga tdk bisa dilakukan pengiriman surat ke sesama pengguna simaya

**Comment by dotovr** [comment]
Terima kasih pak

**Comment by dirr** [comment]
Terimakasih
