### ISSUE TITLE
Data/dokumen yang synced (didapat dari sinkronisasi) perlu disembunyikan / tidak ditampilkan / tidak bisa diedit

### ISSUE THREAD

**Issue by herpiko** [simaya/simaya#287]
Atau tidak ditampilkan sekalian di laman daftar pengguna? (namun tetap muncul di modul name-chooser/recipient).

**Comment by mdamt** [comment]
Disembunyikan saja pak. Demikian juga dengan instansi.

**Comment by herpiko** [comment]
Karena kemarin tidak jadi pakai cara "synced" atau "remote", sebaiknya data ini diinspeksi dengan cara bagaimana? Saat instansi dibuat (pada model lokal dengan installationId), tidak ada installationId yang ditempelkan. Tidak seperti user.

**Comment by mdamt** [comment]
Dari nama instansi yang ada pada node saja pak

**Comment by dotovr** [comment]
Terima kasih pak
