### ISSUE TITLE
File attachment surat hilang pada saat masuk pemeriksaan surat

### ISSUE THREAD

**Issue by dirr** [simaya/simaya#291]
Proses terjadi untuk alur surat keluar, pembuatan surat keluar (konsep), dengan mengupload file lampiran di attachment surat. Setelah disimpan surat berhasil di proses ke pemeriksa selanjutnya tetapi attachment surat yang diupload di awal hilang pada saat masuk ke pemeriksa surat

**Comment by dotovr** [comment]
Terima kasih pak
