### ISSUE TITLE
Konsep Surat tidak masuk ke User Kewenangan Tata Usaha

### ISSUE THREAD

**Issue by dirr** [simaya/simaya#292]
Terjadi pada saat pembuatan Surat Keluar, Konsep Surat Keluar yang dibuat tidak masuk ke dalam user Tata Usaha
Pada saat dicek di konsep surat-> pemeriksa surat untuk user Tata Usaha "Undefined Nama Usernya"
![screen shot 2015-01-15 at 10 12 31 am](https://cloud.githubusercontent.com/assets/8622097/5752015/d5158f18-9c9f-11e4-808f-1d40631492bb.png)

Secara Struktur Pengguna tampilan spt dibawah ini
![screen shot 2015-01-15 at 10 20 14 am](https://cloud.githubusercontent.com/assets/8622097/5752024/242ced26-9ca0-11e4-8cec-37b9f15e8e5c.png)

**Comment by emhaye** [comment]
Bisa dicoba kembali?
Saya lihat konsep suratnya masuk ke Tata usaha
