### ISSUE TITLE
Kumpulan BUG simaya 4 dari FB Simaya

### ISSUE THREAD

**Issue by litanurdiani** [simaya/simaya#297]
1.	Simaya lemot dan tiba-tiba suka log out pada saat diakses
2.	Simaya suka bad gateway pada saat diakses (sama seperti di simaya 3)
3.	Simaya cloud dipekanbaru :
        - Sering terjadi error pada saat edit user
        - Pada saat membuat surat internal dan memilih penerima pada SKPD di Kota Pekanbaru,   muncul SKPD lain di luar Kota Pekanbaru.
4.	Cara mengatur spasi didalam surat keluar
5.	Nama penerima disposisi via smartphone tidak keluar

**Comment by princeofgiri** [comment]
coba buat tiketnya satu masalah satu tiket. saya tutup tiket ini.
