### ISSUE TITLE
Simaya lemot

### ISSUE THREAD

**Issue by litanurdiani** [simaya/simaya#298]
Simaya lemot dan tiba-tiba suka log out pada saat diakses

**Comment by mdamt** [comment]
Silakan dilengkapi sesuai S.O.P: https://github.com/simaya/simaya/wiki/Pedoman-Menulis-Tiket

**Comment by princeofgiri** [comment]
* ini silahkan dikomunikasikan dengan pihak infrastruktur (sudah dibahas juga di grup whatssapp)

cc @dirr

**Comment by litanurdiani** [comment]
Mohon Maaf akan diperbaiki cara penulisannya
