### ISSUE TITLE
Penulisan Membuat Surat Keluar

### ISSUE THREAD

**Issue by litanurdiani** [simaya/simaya#301]
- Mohon pencerahan admin simaya kominfo. kami sudah buat surat pas kami cetak tidak bisa hanya - kertas kosong. apa karena kami pakai simaya v3
- Cara mengatur spasi didalam surat keluar

**Comment by princeofgiri** [comment]
* apakah semua dependensinya sudah dipasang semua? versi 3 harap dinaikkan ke versi 4
* di versi 3 tidak mendukung
