### ISSUE TITLE
Cetak disposisi tombol cetak terpotong

### ISSUE THREAD

**Issue by simaya** [simaya/simaya#306]
Untuk cetak disposisi,masih ada beberapa masalah : (contoh GUI cetak yang diharapkan #216)
1. tombol cetak terpotong (browser : chrome)
2. tidak ada kop
3. GUI tidak sesuai contoh
![screen shot 2015-01-19 at 8 06 40 am](https://cloud.githubusercontent.com/assets/8026127/5794836/1f534d62-9fb2-11e4-8fe4-d610a4946103.png)

**Comment by cho2** [comment]
> 1. tombol cetak terpotong (browser : chrome)

di peramban Chrome, tombol cetak tidak terpotong

![cuplikan layar dari 2015-01-28 13 45 16](https://cloud.githubusercontent.com/assets/6271071/5933488/f1b8fba6-a6f3-11e4-99c2-b3b48e074d2e.png)

> 1. tidak ada kop

tiket #216 masih terbuka (kop memang belum ada) 

> 1. GUI tidak sesuai contoh

#134 (dibuat generik)
