### ISSUE TITLE
siMAYA-L: sinkronisasi tidak boleh menimpa data lokal yang ditandai dengan install_id

### ISSUE THREAD

**Issue by dotovr** [simaya/simaya#309]
### Data master
* Di lokal data hasil impor dari master, kemudian jalankan script migrasi untuk menandai dengan install_id tidak boleh ditimpa oleh data master saat sinkron 
* Data yang memiliki install_id yang ada di lokal tidak boleh ditimpa oleh data master saat sinkron

### Data master + lokal lain (install_id system lain)
* Saat proses sinkron harus memeriksa install_id system, jika data memiliki install_id system tidak boleh ditimpa oleh data lokal lain saat sinkron

**Comment by herpiko** [comment]
- skrip migrasi untuk menandai data milik lokal dengan origin : installationId, yaitu hanya user, instansi, dan jabatan.
- pusat tidak bisa memodifikasi data yang memiliki origin : installationId. data dengan embel-embel installationId hanya bisa dimodifikasi di tempat asal muasalnya (sistem dengan installationId sama)
- saat sinkronisasi di lokal, data yang memiliki origin : installationId dan installationIdnya sama dengan sistem, diskip supaya tidak masuk sistem.

**Comment by herpiko** [comment]
query untuk ekspor data instansi lokal dari master, kemudian impor di simaya lokal.

```
mongoexport -d simayamaster --collection user -q "{'profile.organization':{'\$regex':'^Kabupaten Gunung Lor'}}"
mongoexport -d simayamaster --collection jobTitle -q "{organization:{'\$regex':'^Kabupaten Gunung Lor'}}
mongoexport -d simaya --collection organization -q "{'path':{'\$regex':'^Kabupaten Gunung Lor'}}"
```

**Comment by dotovr** [comment]
Terima kasih pak
