### ISSUE TITLE
Cetak surat masuk selalu bad gateway

### ISSUE THREAD

**Issue by litanurdiani** [simaya/simaya#314]
Tampilan surat masuk apabila ingin mencetak maka akan muncul Bad Gateway
![tata usaha 2](https://cloud.githubusercontent.com/assets/9671051/5831877/e0d03614-a16d-11e4-9c0e-5148a80e7fcf.png)

![tata usaha 1](https://cloud.githubusercontent.com/assets/9671051/5831883/f62b85f4-a16d-11e4-8baf-4fb7899f8300.jpg)

**Comment by emhaye** [comment]
Saat ini sudah bisa dicetak,

Mohon dicoba kembali
