### ISSUE TITLE
Bug komentar

### ISSUE THREAD

**Issue by bonovasuharko** [simaya/simaya#316]
Setiap kali mengirim komentar tercetak 2 kali

![img-20150122-wa0003](https://cloud.githubusercontent.com/assets/9956549/5848880/3e25831c-a210-11e4-83a7-e39eb3f34031.jpg)

**Comment by cho2** [comment]
![cuplikan layar dari 2015-01-28 14 00 10](https://cloud.githubusercontent.com/assets/6271071/5933673/60852936-a6f6-11e4-8ccf-f71c92212cb5.png)

bisa dicoba kembali, jika masih terkirim dua kali, silakan dibuka kembali tiketnya
